theme: jekyll-theme-hacker
title: Curtual Reality
description: You can follow me on [Github](https://github.com/CurtisDeCastro/curtisdecastro.github.io/edit/main/index.md) or [LinkedIn](https://linkedin.com/in/curtis415) to see my latest work first.
