theme: jekyll-theme-hacker
title: Curtual Reality
description: I am a Software / IoT Engineer looking to develop practical applications for Computer Vision, AI, Big Data, UAVs, Robotics, and Aerospace/Defense technology.
